#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER admin;
	ALTER ROLE admin WITH PASSWORD 'admin';
	SELECT 'CREATE DATABASE "$POSTGRES_DB"' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '"$POSTGRES_DB"');
	GRANT ALL PRIVILEGES ON DATABASE btb TO admin;
	GRANT ALL ON SCHEMA public TO admin;
EOSQL